name: Classroom Autograding

name: classroom-autograding

on:
  push:
    branches:
      - '**'

jobs:
  autograde:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Ensure grader source exists
        run: |
          if [ ! -f grader/Grader.java ]; then
            echo "grader/Grader.java not found in repository. Please add grader/Grader.java to the repo."; exit 1
          fi
name: Classroom Autograding

on:
  push:
    branches:
      - '**'

jobs:
  autograde:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Ensure grader source exists
        run: |
          if [ ! -f grader/Grader.java ]; then
            echo "grader/Grader.java not found in repository. Please add grader/Grader.java to the repo."; exit 1
          fi

      - name: Compile grader
        run: |
          mkdir -p grader/classes
          javac -d grader/classes grader/Grader.java

      - name: Compile student Java files
        name: classroom-autograding

        on:
          push:
            branches:
              - "**"

        jobs:
          autograde:
            runs-on: ubuntu-latest
            steps:
              - name: Checkout repository
                uses: actions/checkout@v4

              - name: Set up JDK 17
                uses: actions/setup-java@v4
                with:
                  distribution: temurin
                  java-version: '17'

              - name: Ensure grader source exists
                run: |
                  if [ ! -f grader/Grader.java ]; then
                    echo "grader/Grader.java not found in repository. Please add grader/Grader.java to the repo."; exit 1
                  fi

              - name: Compile grader
                run: |
                  mkdir -p grader/classes
                  javac -d grader/classes grader/Grader.java

              - name: Compile student Java files
                name: classroom-autograding

                on:
                  push:
                    branches:
                      - "**"

                jobs:
                  autograde:
                    runs-on: ubuntu-latest
                    steps:
                      - name: Checkout repository
                        uses: actions/checkout@v4

                      - name: Set up JDK 17
                        uses: actions/setup-java@v4
                        with:
                          distribution: temurin
                          java-version: '17'

                      - name: Ensure grader source exists
                        run: |
                          if [ ! -f grader/Grader.java ]; then
                            echo "grader/Grader.java not found in repository. Please add grader/Grader.java to the repo."; exit 1
                          fi

                      - name: Compile grader
                        run: |
                          mkdir -p grader/classes
                          javac -d grader/classes grader/Grader.java

                      - name: Compile student Java files
                        run: |
                          mkdir -p classes
                          files=$(find . -name "*.java" -not -path "./grader/*" -not -path "./.github/*" -not -path "./target/*") || true
                          if [ -z "$files" ]; then
                            echo "No student Java files found to compile."; exit 1
                          fi
                          javac -d classes $files

                      - name: Run grader and capture output
                        id: run_grader
                        run: |
                          CP=grader/classes:classes
                          java -cp "$CP" Grader | tee grader-output.txt
                          cat grader-output.txt

                      - name: Parse score and fail on incomplete
                        run: |
                          final=$(tail -n 1 grader-output.txt || true)
                          echo "Final line: $final"
                          if [[ $final =~ ([0-9]+)\s*/\s*([0-9]+) ]]; then
                            achieved=${BASH_REMATCH[1]}
                            total=${BASH_REMATCH[2]}
                            if [ "$achieved" -lt "$total" ]; then
                              echo "Score ($achieved/$total) is less than full. Failing check."; exit 1
                            else
                              echo "Full score achieved ($achieved/$total).";
                            fi
                          else
                            echo "Could not parse final score."; exit 1
                          fi
